name: Deploy en AWS Lightsail
on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conexion SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Despliegue en Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.164.62.138 << 'EOF'
          cd /var/www/html
          sudo rm -rf *
          git clone https://github.com/guerreroTorito/PaginWeb.git .
          EOF