name: publicar contenidop en githuboages 
on:
  push:
      branches: ["master"]

permissions: 
  contents: read
  pages: write
  id-token: write

concurrency: 
    group: pages
    cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: githup-pages
      url: ${{ steps.deployment.outputs.page.url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Instalar Pages
        uses: actions/configure-pages@v5
      - name: Cargar Pagina
        uses: actions/apload-pages-artifact@v3
        with:
          path : '.'
      - name: desplegar Pagina
        id: deployment
        uses: actions/deploy-pages@v4 

